name = "NetworkTrading"
uuid = "c51a1053-3d0b-4f24-aa10-034b6d6fd53d"
authors = ["Edwin Lock <mail@edwinlock.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
