name = "NetworkTrading"
uuid = "c51a1053-3d0b-4f24-aa10-034b6d6fd53d"
authors = ["Edwin Lock <edwinlock@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
